### ISSUE TITLE
[Types] add tsdoc to some types to help understand their purpose

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#10525]
**Do you want to request a *feature* or report a *bug*?**
types / documentaion

**What is the current behavior?**
add tsdoc (more documentation) and examples to types, like:
- [x] [`EnforceDocument`](https://github.com/Automattic/mongoose/blob/c36bd644ca33bef4bcc49ce59f046ad0f0a0fde4/index.d.ts#L755) (fixed with #10843)
- [x] [`FilterQuery`](https://github.com/Automattic/mongoose/blob/c36bd644ca33bef4bcc49ce59f046ad0f0a0fde4/index.d.ts#L2499) (fixed with #11457)
- [x] [`UpdateQuery`](https://github.com/Automattic/mongoose/blob/c36bd644ca33bef4bcc49ce59f046ad0f0a0fde4/index.d.ts#L2552) (fixed with #11457)
- [x] [`LeanDocument`](https://github.com/Automattic/mongoose/blob/c36bd644ca33bef4bcc49ce59f046ad0f0a0fde4/index.d.ts#L2583) (fixed with #11457)

Why?
because those types are commonly used outside of mongoose's internals for factory functions or to add custom query functions, it would be really helpful if there was some documentation noting what these types do (and maybe what they dont do) plus maybe some examples ([`@example`](https://tsdoc.org/pages/tags/example/)) (it would be helpful in debugging type issues)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose 5.13.5

**Comment by Moisei-Shkil** [comment]
Handled on https://github.com/Automattic/mongoose/pull/11457

**Comment by hasezoey** [comment]
fixed by #11457
